// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:hollat/login/data/database/service_config_database.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ServiceConfigDatabaseAdapter());
  }
}
